spring:
  datasource:
    url: jdbc:sqlite:D:/zhuomian/homework/model-training.db
    driver-class-name: org.sqlite.JDBC



uploadAddress:
  D:/zhuomian/homework/upload/homework/
certificateAddress:
  D:/zhuomian/homework/upload/certificate/